### ISSUE TITLE
Find examples of TMs and push to this repo

### ISSUE THREAD

**Issue by DinisCruz** [OWASP/threat-model-cookbook#5]

**Comment by swierckx** [comment]
Here are some examples I collected over time

Template Sample: Web Application Threat Model:
https://docs.microsoft.com/en-us/previous-versions/msp-n-p/ff649779(v=pandp.10)

OAuth 2.0 Threat Model and Security Considerations:
https://tools.ietf.org/html/rfc6819

PTA Risk Analysis Sample Reports, computerized system for publishing the daily currency exchange rates:
http://www.ptatechnologies.com/Documents/PTACurrencySample.pdf

Several examples related to BizTalk server:
https://docs.microsoft.com/en-us/biztalk/core/sample-scenarios-for-threat-model-analysis

A Threat Model Analysis of EPC-based Information Sharing Networks:
http://www.bridge-project.eu/data/File/BRIDGE_WP04_Threat_Model_Analysis.pdf

**Comment by jmarcil** [comment]
Current target is to gather models from people who own them because we publish as open source.

I want original content 😄
